### ISSUE TITLE
Add filtering by OBS ID in IRIS loader

### ISSUE THREAD

**Issue by Cadair** [glue-viz/glue-solar#10]
See #7

**Comment by abhijeetmanhas** [comment]
Can I work on this? I have to add a function in this `/glue_solar/instruments/iris/iris_loader.py` which can return raster or sji data based on observation index ?

**Comment by Cadair** [comment]
yeah and update the GUI in some way to expose it.

**Comment by abhijeetmanhas** [comment]
How can we test solar plugins on glue, how can we build it? Running setup.py file is enough?

**Comment by Cadair** [comment]
For automated testing see #11 I think for a lot of it you will need to start it up and give it some iris data and see how it goes.

**Comment by Raahul-Singh** [comment]
@abhijeetmanhas Are you still on this?

**Comment by abhijeetmanhas** [comment]
> @abhijeetmanhas Are you still on this?

yes, :) I have made changes, and now finding ways to expose it in GUI.

**Comment by kakirastern** [comment]
Let me add this feature as part of the GSoC 2020 `glue-solar` project soon...

**Comment by kakirastern** [comment]
In fact let me tackle this next...

**Comment by kakirastern** [comment]
@Cadair I think I know how to obtain the `OBSID` for the IRIS data... In fact, I was doing this at some point in a recent `glue-solar` PR, but reverted since I was not sure about this (and was not aware of this issue). Should I simply add this `OBSID` to the "tag" used for each observation for the filtering? If so, I could open a PR on it soon.

**Comment by kakirastern** [comment]
Just opened a PR for this issue.
